version: '3.8'

services:
  app:
    build: .
    container_name: sportif_backend
    ports:
      - "8002:8002"
    # Enables host.docker.internal to resolve the linux host IP
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # Database Config (Passed from your .env file)
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_SSLMODE=${DB_SSLMODE}
      
      # App Config
      - PORT=8002
      - JWT_SECRET=${JWT_SECRET}
      
      # Backblaze B2 Config
      - B2_ENDPOINT=${B2_ENDPOINT}
      - B2_REGION=${B2_REGION}
      - B2_BUCKET_NAME=${B2_BUCKET_NAME}
      - B2_KEY_ID=${B2_KEY_ID}
      - B2_APPLICATION_KEY=${B2_APPLICATION_KEY}
      
      # Redis Config (Passed from your .env file)
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
    networks:
      - e-c-deployerscript_e-commerce-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  e-c-deployerscript_e-commerce-network:
    external: true